# Generated by Django 5.0.4 on 2024-05-29 11:46

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('html', models.TextField()),
                ('css', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 29, 17, 16, 46, 477239))),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2024, 5, 29, 17, 16, 46, 477239))),
            ],
        ),
    ]
