# Generated by Django 5.0.4 on 2024-05-29 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoCodeBuilderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 17, 17, 9, 617544)),
        ),
        migrations.AlterField(
            model_name='pages',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 29, 17, 17, 9, 617544)),
        ),
    ]
