# Generated by Django 5.0.4 on 2024-05-30 04:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NoCodeBuilderApp', '0005_alter_pages_created_at_alter_pages_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 9, 54, 43, 716166)),
        ),
        migrations.AlterField(
            model_name='pages',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 30, 9, 54, 43, 717485)),
        ),
    ]
